# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-15 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Que',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wenti', models.CharField(max_length=100)),
                ('daan1', models.CharField(max_length=100)),
                ('daan2', models.CharField(max_length=100)),
                ('daan3', models.CharField(max_length=100)),
                ('daan4', models.CharField(max_length=100)),
            ],
        ),
    ]
