# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-15 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='que',
            name='wenti',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
