# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-22 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0002_auto_20180815_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jishu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ji_shu', models.IntegerField()),
            ],
        ),
    ]
