# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-22 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0003_jishu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jishu',
            name='ji_shu',
            field=models.IntegerField(default=0),
        ),
    ]
