# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-13 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
